namespace: argocd

resources:
  - certificate.yaml
  - namespace.yaml
  - install.yaml
  - ingress.yaml
  - repository-secret.yaml
  - operator-postgres.yaml
  - app-nfs-provisioner.yaml
  - app-formbricks.yaml