apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excalidraw
spec:
  project: default
  source:
    repoURL: replace-me
    targetRevision: main
    path: apps/overlays/prod/excalidraw
  destination:
    server: https://kubernetes.default.svc
    namespace: excalidraw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true