apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr
spec:
  project: default
  source:
    repoURL: replace-me
    targetRevision: main
    path: apps/overlays/prod/n8n
  destination:
    server: https://kubernetes.default.svc
    namespace: overseerr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true