# This job runs when we perform a kustomize build / apply of this folder.
# It will try to ping the mysql server every 5 seconds for up to 3 minutes,
# and then fail. If it fails, it will retry 1 time (for another 3 minutes).

# If the server responds to the ping, the script will attempt to login, create
# the specified app database and app user (identified by password), then grant
# the app user all permissions on the app database.

apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: mysql-operator

# ... the remainder of the job is specified in overlays/db-init-job.yaml.
# Outside of examples, overlays are not committed to a public repo to avoid
# disclosure of information which might help an adversary.