apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
