apiVersion: v1
kind: Secret
metadata:
  name: domain-zbm001-cert
  annotations:
    replicator.v1.mittwald.de/replicate-from: cert-manager/domain-zbm001-cert
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""