apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: formbricks-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: microk8s-hostpath
