# For some reason, if this gets reapplied, it will empty the tls.key and tls.crt fields.
# Resolution for this is to delete the secret and reapply this configuration. The replicator
# will detect the new secret and populate the fields again.

# Alternatively, you could delete the cert-manager secret. It will be automatically recreated,
# and this should trigger a cascade from the replicator, replacing all cert values for all linked
# secrets.

apiVersion: v1
kind: Secret
metadata:
  name: domain-zbm001-cert
  annotations:
    replicator.v1.mittwald.de/replicate-from: cert-manager/domain-zbm001-cert
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""