apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: formbricks

resources:
  - path-to-formbricks-base

patches:
  - path: patch-configmap-domain.yaml
  - path: patch-ingress-host.yaml
  - path: patch-tls-secret-replicator.yaml
