apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: repsales
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: docker.io/library/redis:8
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redisdata
              mountPath: /data
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: paperless-redisdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: repsales
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: docker.io/library/postgres:17
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: paperless
            - name: POSTGRES_USER
              value: paperless
            - name: POSTGRES_PASSWORD
              value: REPLACE_ME
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: paperless-pgdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: repsales
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PAPERLESS_URL
              value: "https://repsales-paperless.zbmowrey.com"
            - name: PAPERLESS_REDIS
              value: redis://broker:6379
            - name: PAPERLESS_DBHOST
              value: db
            - name: PAPERLESS_DBPASS
              value: REPLACE_ME
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
            - name: export
              mountPath: /usr/src/paperless/export
            - name: consume
              mountPath: /usr/src/paperless/consume
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: media
          persistentVolumeClaim:
            claimName: paperless-media
        - name: export
          hostPath:
            path: /mnt/paperless/export
            type: DirectoryOrCreate
        - name: consume
          hostPath:
            path: /mnt/paperless/consume
            type: DirectoryOrCreate
