apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: repsales
  labels:
    app: broker
spec:
  type: ClusterIP
  selector:
    app: broker
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: repsales
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: repsales
  labels:
    app: webserver
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - name: http
      port: 8000
      targetPort: 8000
