apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zbmowrey-com-cert
  namespace: cert-manager
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "*"
spec:
  secretName: replace-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: replace-me-domain
  dnsNames:
    - replace-me-domain
    - replace-me-domain-wildcard
