apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zbmowrey-com-cert
  namespace: cert-manager
spec:
  secretName: domain-zbm001-cert
  commonName: zbmowrey.com
  dnsNames:
    - zbmowrey.com
    - '*.zbmowrey.com'
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"
      replicator.v1.mittwald.de/replication-allowed-namespaces: '*'