apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: secret-name-to-create
  namespace: default
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: '*'
spec:
  itemPath: "vaults/YourVaultName/items/your-smtp-secret"
  # The smtp secret should contain the following fields:
  # - host
  # - port
  # - user
  # - password
