apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: slack-webhook-url
  namespace: default
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: '*'
spec:
  itemPath: "vaults/Kubernetes/items/slack-webhook-url"