apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-zbm001-cert
  namespace: cert-manager
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "*"
spec:
  secretName: replace-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: replace-me-domain
  dnsNames:
    - replace-me-domain
    - replace-me-domain-wildcard
---
apiVersion: v1
kind: Secret
metadata:
  name: domain-zbm001-cert
  namespace: ingress-nginx
  annotations:
    replicator.v1.mittwald.de/replicate-from: cert-manager/domain-zbm001-cert
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""