resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - certificate.yaml

patches:
  # Patch to switch the argocd-server service type to ClusterIP
  - path: server-service-patch.yaml