# 1Password Operator + Connect Server allows us to automatically sync
# secrets from our 1Password vault to kubernetes secrets. The polling
# frequency to 1Password is 10 minutes by default. To bypass this, you
# can configure a shorter polling frequency, or you can make any change
# to the OnePasswordItem, which will trigger a refresh. Alternatively,
# delete the 1password operator pod - it will re-sync all secrets on
# init.

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: test-user-secret
spec:
  itemPath: "vaults/Kubernetes/items/test-user-secret"