apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
spec:
  project: default
  info:
    - name: "Description"
      value: "Paperless-NGX is a DMS (Document Management System) for archiving and indexing documents."
    - name: "Application"
      value: "paperless-ngx"
    - name: "Repository"
      value: "https://github.com/zbmowrey/lab"
    - name: "Environment"
      value: "home-lab-001"
  source:
    repoURL: replace-me
    targetRevision: main
    path: overlays/prod/paperless
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true