apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: ghost-db
  namespace: mysql-operator
  finalizers:
    - percona.com/delete-pxc-pods-in-order
spec:
  crVersion: 1.17.0
  secretsName: mysql-database-users
  unsafeFlags:
    pxcSize: true
    proxySize: true
  tls:
    enabled: true
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 1                   # <-- single node
    image: percona/percona-xtradb-cluster:8.0.41-32.1
    affinity:
      podAntiAffinity: null
    autoRecovery: true
    resources:
      requests:
        memory: 1G
        cpu: 500m
    podDisruptionBudget:
      maxUnavailable: 0
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
    gracePeriod: 600
  haproxy:
    enabled: true
    size: 1
    affinity:
      podAntiAffinity: null
    image: percona/haproxy:2.8.14
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
    podDisruptionBudget:
      maxUnavailable: 0
    gracePeriod: 30
  proxysql:
    enabled: false
    size: 1
    image: percona/proxysql2:2.7.1
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2G
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.17.0-logcollector-fluentbit4.0.0
    resources:
      requests:
        memory: 100M
        cpu: 200m
  pmm:
    enabled: false
    image: percona/pmm-client:2.44.0
    serverHost: monitoring-service
    resources:
      requests:
        memory: 150M
        cpu: 300m
  backup:
    image: percona/percona-xtradb-cluster-operator:1.17.0-pxc8.0-backup-pxb8.0.35
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            storageClassName: nfs-client
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 6G
    pitr:
      enabled: false
      storageName: fs-pvc
      timeBetweenUploads: 60
      timeoutSeconds: 60
    schedule:
      - name: "daily-backup"
        schedule: "0 0 * * *"
        keep: 5
        storageName: fs-pvc
