# Do NOT apply a namespace here. See NAMESPACING.md for details.

resources:
  - namespace.yaml
  - tls-certificate-secret.yaml
  - smtp-secret.yaml
  - pvc.yaml
  - database.yaml
  # After the initial deployment, we comment this so that ArgoCD won't see it as failing when the job TTLs out. 
  # - db-init-job.yaml
  - user-secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml