apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-uploads
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
