apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: docmost
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  enableSuperuserAccess: true
  storage:
    size: 4Gi
    storageClass: microk8s-hostpath
  bootstrap:
    initdb:
      database: docmost
      owner: postgres
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB
