apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docmost
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: docmost
spec:
  ingressClassName: public
  tls:
    - hosts:
        - replace-me
      secretName: replace-me
  rules:
    - host: replace-me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docmost
                port:
                  number: 3000
