apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-storage-pvc
  labels:
    app: docmost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client