apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: formbricks-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: openebs
